// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Metadata -->Metadata Roksbox resource.
 * For more information refer to [Metadata](https://wiki.servarr.com/lidarr/settings#metadata) and [ROKSBOX](https://wiki.servarr.com/lidarr/supported#roksboxmetadata).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = new sonarr.index.Sonarr_metadata_roksbox("example", {
 *     enable: true,
 *     name: "Example",
 *     trackMetadata: true,
 *     artistImages: false,
 *     albumImages: true,
 * });
 * ```
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import lidarr:Metadata/metadataRoksbox:MetadataRoksbox example 1
 * ```
 */
export class MetadataRoksbox extends pulumi.CustomResource {
    /**
     * Get an existing MetadataRoksbox resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MetadataRoksboxState, opts?: pulumi.CustomResourceOptions): MetadataRoksbox {
        return new MetadataRoksbox(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lidarr:Metadata/metadataRoksbox:MetadataRoksbox';

    /**
     * Returns true if the given object is an instance of MetadataRoksbox.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MetadataRoksbox {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MetadataRoksbox.__pulumiType;
    }

    /**
     * Album images flag.
     */
    public readonly albumImages!: pulumi.Output<boolean>;
    /**
     * Artist images flag.
     */
    public readonly artistImages!: pulumi.Output<boolean>;
    /**
     * Enable flag.
     */
    public readonly enable!: pulumi.Output<boolean>;
    /**
     * Metadata name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * List of associated tags.
     */
    public readonly tags!: pulumi.Output<number[]>;
    /**
     * Track metadata flag.
     */
    public readonly trackMetadata!: pulumi.Output<boolean>;

    /**
     * Create a MetadataRoksbox resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MetadataRoksboxArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MetadataRoksboxArgs | MetadataRoksboxState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MetadataRoksboxState | undefined;
            resourceInputs["albumImages"] = state ? state.albumImages : undefined;
            resourceInputs["artistImages"] = state ? state.artistImages : undefined;
            resourceInputs["enable"] = state ? state.enable : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["trackMetadata"] = state ? state.trackMetadata : undefined;
        } else {
            const args = argsOrState as MetadataRoksboxArgs | undefined;
            if ((!args || args.albumImages === undefined) && !opts.urn) {
                throw new Error("Missing required property 'albumImages'");
            }
            if ((!args || args.artistImages === undefined) && !opts.urn) {
                throw new Error("Missing required property 'artistImages'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.trackMetadata === undefined) && !opts.urn) {
                throw new Error("Missing required property 'trackMetadata'");
            }
            resourceInputs["albumImages"] = args ? args.albumImages : undefined;
            resourceInputs["artistImages"] = args ? args.artistImages : undefined;
            resourceInputs["enable"] = args ? args.enable : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["trackMetadata"] = args ? args.trackMetadata : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MetadataRoksbox.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MetadataRoksbox resources.
 */
export interface MetadataRoksboxState {
    /**
     * Album images flag.
     */
    albumImages?: pulumi.Input<boolean>;
    /**
     * Artist images flag.
     */
    artistImages?: pulumi.Input<boolean>;
    /**
     * Enable flag.
     */
    enable?: pulumi.Input<boolean>;
    /**
     * Metadata name.
     */
    name?: pulumi.Input<string>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Track metadata flag.
     */
    trackMetadata?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a MetadataRoksbox resource.
 */
export interface MetadataRoksboxArgs {
    /**
     * Album images flag.
     */
    albumImages: pulumi.Input<boolean>;
    /**
     * Artist images flag.
     */
    artistImages: pulumi.Input<boolean>;
    /**
     * Enable flag.
     */
    enable?: pulumi.Input<boolean>;
    /**
     * Metadata name.
     */
    name: pulumi.Input<string>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Track metadata flag.
     */
    trackMetadata: pulumi.Input<boolean>;
}
