// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Metadata -->Metadata Kodi resource.
 * For more information refer to [Metadata](https://wiki.servarr.com/lidarr/settings#metadata) and [KODI](https://wiki.servarr.com/lidarr/supported#xbmcmetadata).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@maienm/pulumi-lidarr";
 *
 * const example = new lidarr.metadata.MetadataKodi("example", {
 *     albumImages: true,
 *     albumMetadata: false,
 *     artistImages: true,
 *     artistMetadata: true,
 *     enable: true,
 *     name: "Example",
 * });
 * ```
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import lidarr:Metadata/metadataKodi:MetadataKodi example 1
 * ```
 */
export class MetadataKodi extends pulumi.CustomResource {
    /**
     * Get an existing MetadataKodi resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MetadataKodiState, opts?: pulumi.CustomResourceOptions): MetadataKodi {
        return new MetadataKodi(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lidarr:Metadata/metadataKodi:MetadataKodi';

    /**
     * Returns true if the given object is an instance of MetadataKodi.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MetadataKodi {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MetadataKodi.__pulumiType;
    }

    /**
     * Album images flag.
     */
    public readonly albumImages!: pulumi.Output<boolean>;
    /**
     * Album metadata flag.
     */
    public readonly albumMetadata!: pulumi.Output<boolean>;
    /**
     * Artist images flag.
     */
    public readonly artistImages!: pulumi.Output<boolean>;
    /**
     * Artist metadata flag.
     */
    public readonly artistMetadata!: pulumi.Output<boolean>;
    /**
     * Enable flag.
     */
    public readonly enable!: pulumi.Output<boolean>;
    /**
     * Metadata name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * List of associated tags.
     */
    public readonly tags!: pulumi.Output<number[]>;

    /**
     * Create a MetadataKodi resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MetadataKodiArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MetadataKodiArgs | MetadataKodiState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MetadataKodiState | undefined;
            resourceInputs["albumImages"] = state ? state.albumImages : undefined;
            resourceInputs["albumMetadata"] = state ? state.albumMetadata : undefined;
            resourceInputs["artistImages"] = state ? state.artistImages : undefined;
            resourceInputs["artistMetadata"] = state ? state.artistMetadata : undefined;
            resourceInputs["enable"] = state ? state.enable : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as MetadataKodiArgs | undefined;
            if ((!args || args.albumImages === undefined) && !opts.urn) {
                throw new Error("Missing required property 'albumImages'");
            }
            if ((!args || args.albumMetadata === undefined) && !opts.urn) {
                throw new Error("Missing required property 'albumMetadata'");
            }
            if ((!args || args.artistImages === undefined) && !opts.urn) {
                throw new Error("Missing required property 'artistImages'");
            }
            if ((!args || args.artistMetadata === undefined) && !opts.urn) {
                throw new Error("Missing required property 'artistMetadata'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["albumImages"] = args ? args.albumImages : undefined;
            resourceInputs["albumMetadata"] = args ? args.albumMetadata : undefined;
            resourceInputs["artistImages"] = args ? args.artistImages : undefined;
            resourceInputs["artistMetadata"] = args ? args.artistMetadata : undefined;
            resourceInputs["enable"] = args ? args.enable : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MetadataKodi.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MetadataKodi resources.
 */
export interface MetadataKodiState {
    /**
     * Album images flag.
     */
    albumImages?: pulumi.Input<boolean>;
    /**
     * Album metadata flag.
     */
    albumMetadata?: pulumi.Input<boolean>;
    /**
     * Artist images flag.
     */
    artistImages?: pulumi.Input<boolean>;
    /**
     * Artist metadata flag.
     */
    artistMetadata?: pulumi.Input<boolean>;
    /**
     * Enable flag.
     */
    enable?: pulumi.Input<boolean>;
    /**
     * Metadata name.
     */
    name?: pulumi.Input<string>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
}

/**
 * The set of arguments for constructing a MetadataKodi resource.
 */
export interface MetadataKodiArgs {
    /**
     * Album images flag.
     */
    albumImages: pulumi.Input<boolean>;
    /**
     * Album metadata flag.
     */
    albumMetadata: pulumi.Input<boolean>;
    /**
     * Artist images flag.
     */
    artistImages: pulumi.Input<boolean>;
    /**
     * Artist metadata flag.
     */
    artistMetadata: pulumi.Input<boolean>;
    /**
     * Enable flag.
     */
    enable?: pulumi.Input<boolean>;
    /**
     * Metadata name.
     */
    name: pulumi.Input<string>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
}
