// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->Single Metadata Profile.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getMetadataProfile({
 *     name: "Example",
 * });
 * ```
 */
export function getMetadataProfile(args: GetMetadataProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetMetadataProfileResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("lidarr:Profiles/getMetadataProfile:getMetadataProfile", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getMetadataProfile.
 */
export interface GetMetadataProfileArgs {
    /**
     * Metadata Profile name.
     */
    name: string;
}

/**
 * A collection of values returned by getMetadataProfile.
 */
export interface GetMetadataProfileResult {
    /**
     * Metadata Profile ID.
     */
    readonly id: number;
    /**
     * Metadata Profile name.
     */
    readonly name: string;
    /**
     * Primary album types.
     */
    readonly primaryAlbumTypes: number[];
    /**
     * Release statuses.
     */
    readonly releaseStatuses: number[];
    /**
     * Secondary album types.
     */
    readonly secondaryAlbumTypes: number[];
}
/**
 * <!-- subcategory:Profiles -->Single Metadata Profile.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getMetadataProfile({
 *     name: "Example",
 * });
 * ```
 */
export function getMetadataProfileOutput(args: GetMetadataProfileOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMetadataProfileResult> {
    return pulumi.output(args).apply((a: any) => getMetadataProfile(a, opts))
}

/**
 * A collection of arguments for invoking getMetadataProfile.
 */
export interface GetMetadataProfileOutputArgs {
    /**
     * Metadata Profile name.
     */
    name: pulumi.Input<string>;
}
