// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->Single available Primary Album Type.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getPrimaryAlbumType({
 *     name: "Single",
 * });
 * ```
 */
export function getPrimaryAlbumType(args: GetPrimaryAlbumTypeArgs, opts?: pulumi.InvokeOptions): Promise<GetPrimaryAlbumTypeResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("lidarr:Profiles/getPrimaryAlbumType:getPrimaryAlbumType", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPrimaryAlbumType.
 */
export interface GetPrimaryAlbumTypeArgs {
    /**
     * PrimaryAlbumType.
     */
    name: string;
}

/**
 * A collection of values returned by getPrimaryAlbumType.
 */
export interface GetPrimaryAlbumTypeResult {
    /**
     * PrimaryAlbumType ID.
     */
    readonly id: number;
    /**
     * PrimaryAlbumType.
     */
    readonly name: string;
}
/**
 * <!-- subcategory:Profiles -->Single available Primary Album Type.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getPrimaryAlbumType({
 *     name: "Single",
 * });
 * ```
 */
export function getPrimaryAlbumTypeOutput(args: GetPrimaryAlbumTypeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPrimaryAlbumTypeResult> {
    return pulumi.output(args).apply((a: any) => getPrimaryAlbumType(a, opts))
}

/**
 * A collection of arguments for invoking getPrimaryAlbumType.
 */
export interface GetPrimaryAlbumTypeOutputArgs {
    /**
     * PrimaryAlbumType.
     */
    name: pulumi.Input<string>;
}
