// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->List all available Primary Album Types.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getPrimaryAlbumTypes({});
 * ```
 */
export function getPrimaryAlbumTypes(opts?: pulumi.InvokeOptions): Promise<GetPrimaryAlbumTypesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("lidarr:Profiles/getPrimaryAlbumTypes:getPrimaryAlbumTypes", {
    }, opts);
}

/**
 * A collection of values returned by getPrimaryAlbumTypes.
 */
export interface GetPrimaryAlbumTypesResult {
    /**
     * Primary album type list.
     */
    readonly elements: outputs.Profiles.GetPrimaryAlbumTypesElement[];
    /**
     * The ID of this resource.
     */
    readonly id: string;
}
