// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->Single available Release Status.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getReleaseStatus({
 *     name: "Official",
 * });
 * ```
 */
export function getReleaseStatus(args: GetReleaseStatusArgs, opts?: pulumi.InvokeOptions): Promise<GetReleaseStatusResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("lidarr:Profiles/getReleaseStatus:getReleaseStatus", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getReleaseStatus.
 */
export interface GetReleaseStatusArgs {
    /**
     * Release Status name.
     */
    name: string;
}

/**
 * A collection of values returned by getReleaseStatus.
 */
export interface GetReleaseStatusResult {
    /**
     * Release Status ID.
     */
    readonly id: number;
    /**
     * Release Status name.
     */
    readonly name: string;
}
/**
 * <!-- subcategory:Profiles -->Single available Release Status.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getReleaseStatus({
 *     name: "Official",
 * });
 * ```
 */
export function getReleaseStatusOutput(args: GetReleaseStatusOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetReleaseStatusResult> {
    return pulumi.output(args).apply((a: any) => getReleaseStatus(a, opts))
}

/**
 * A collection of arguments for invoking getReleaseStatus.
 */
export interface GetReleaseStatusOutputArgs {
    /**
     * Release Status name.
     */
    name: pulumi.Input<string>;
}
