// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->List all available Secondary Album Types.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getSecondaryAlbumTypes({});
 * ```
 */
export function getSecondaryAlbumTypes(opts?: pulumi.InvokeOptions): Promise<GetSecondaryAlbumTypesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("lidarr:Profiles/getSecondaryAlbumTypes:getSecondaryAlbumTypes", {
    }, opts);
}

/**
 * A collection of values returned by getSecondaryAlbumTypes.
 */
export interface GetSecondaryAlbumTypesResult {
    /**
     * Secondary album type list.
     */
    readonly elements: outputs.Profiles.GetSecondaryAlbumTypesElement[];
    /**
     * The ID of this resource.
     */
    readonly id: string;
}
