// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->Single available Secondary Album Type.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getSecondaryAlbumType({
 *     name: "Remix",
 * });
 * ```
 */
export function getSecondaryAlbumType(args: GetSecondaryAlbumTypeArgs, opts?: pulumi.InvokeOptions): Promise<GetSecondaryAlbumTypeResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("lidarr:Profiles/getSecondaryAlbumType:getSecondaryAlbumType", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getSecondaryAlbumType.
 */
export interface GetSecondaryAlbumTypeArgs {
    /**
     * SecondaryAlbumType.
     */
    name: string;
}

/**
 * A collection of values returned by getSecondaryAlbumType.
 */
export interface GetSecondaryAlbumTypeResult {
    /**
     * SecondaryAlbumType ID.
     */
    readonly id: number;
    /**
     * SecondaryAlbumType.
     */
    readonly name: string;
}
/**
 * <!-- subcategory:Profiles -->Single available Secondary Album Type.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.Profiles.getSecondaryAlbumType({
 *     name: "Remix",
 * });
 * ```
 */
export function getSecondaryAlbumTypeOutput(args: GetSecondaryAlbumTypeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSecondaryAlbumTypeResult> {
    return pulumi.output(args).apply((a: any) => getSecondaryAlbumType(a, opts))
}

/**
 * A collection of arguments for invoking getSecondaryAlbumType.
 */
export interface GetSecondaryAlbumTypeOutputArgs {
    /**
     * SecondaryAlbumType.
     */
    name: pulumi.Input<string>;
}
