// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Media Management -->Naming.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@pulumi/lidarr";
 *
 * const example = lidarr.MediaManagement.getNaming({});
 * ```
 */
export function getNaming(opts?: pulumi.InvokeOptions): Promise<GetNamingResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("lidarr:MediaManagement/getNaming:getNaming", {
    }, opts);
}

/**
 * A collection of values returned by getNaming.
 */
export interface GetNamingResult {
    /**
     * Artist folder format.
     */
    readonly artistFolderFormat: string;
    /**
     * Naming ID.
     */
    readonly id: number;
    /**
     * Multi disc track format.
     */
    readonly multiDiscTrackFormat: string;
    /**
     * Lidarr will use the existing file name if false.
     */
    readonly renameTracks: boolean;
    /**
     * Replace illegal characters. They will be removed if false.
     */
    readonly replaceIllegalCharacters: boolean;
    /**
     * Standard track formatss.
     */
    readonly standardTrackFormat: string;
}
