// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Media Management -->Root Folder resource.
 * For more information refer to [Root Folders](https://wiki.servarr.com/lidarr/settings#root-folders) documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@maienm/pulumi-lidarr";
 *
 * const example = new lidarr.mediamanagement.RootFolder("example", {
 *     metadataProfileId: 1,
 *     monitorOption: "future",
 *     name: "Example",
 *     newItemMonitorOption: "all",
 *     path: "/music",
 *     qualityProfileId: 1,
 *     tags: [1],
 * });
 * ```
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import lidarr:MediaManagement/rootFolder:RootFolder example 10
 * ```
 */
export class RootFolder extends pulumi.CustomResource {
    /**
     * Get an existing RootFolder resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RootFolderState, opts?: pulumi.CustomResourceOptions): RootFolder {
        return new RootFolder(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lidarr:MediaManagement/rootFolder:RootFolder';

    /**
     * Returns true if the given object is an instance of RootFolder.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RootFolder {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RootFolder.__pulumiType;
    }

    /**
     * Access flag.
     */
    public /*out*/ readonly accessible!: pulumi.Output<boolean>;
    /**
     * Metadata profile ID.
     */
    public readonly metadataProfileId!: pulumi.Output<number>;
    /**
     * Monitor option.
     */
    public readonly monitorOption!: pulumi.Output<string>;
    /**
     * Root Folder friendly name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * New item monitor option.
     */
    public readonly newItemMonitorOption!: pulumi.Output<string>;
    /**
     * Root Folder absolute path.
     */
    public readonly path!: pulumi.Output<string>;
    /**
     * Quality profile ID.
     */
    public readonly qualityProfileId!: pulumi.Output<number>;
    /**
     * List of associated tags.
     */
    public readonly tags!: pulumi.Output<number[]>;

    /**
     * Create a RootFolder resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RootFolderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RootFolderArgs | RootFolderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RootFolderState | undefined;
            resourceInputs["accessible"] = state ? state.accessible : undefined;
            resourceInputs["metadataProfileId"] = state ? state.metadataProfileId : undefined;
            resourceInputs["monitorOption"] = state ? state.monitorOption : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["newItemMonitorOption"] = state ? state.newItemMonitorOption : undefined;
            resourceInputs["path"] = state ? state.path : undefined;
            resourceInputs["qualityProfileId"] = state ? state.qualityProfileId : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as RootFolderArgs | undefined;
            if ((!args || args.metadataProfileId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'metadataProfileId'");
            }
            if ((!args || args.monitorOption === undefined) && !opts.urn) {
                throw new Error("Missing required property 'monitorOption'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.newItemMonitorOption === undefined) && !opts.urn) {
                throw new Error("Missing required property 'newItemMonitorOption'");
            }
            if ((!args || args.path === undefined) && !opts.urn) {
                throw new Error("Missing required property 'path'");
            }
            if ((!args || args.qualityProfileId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'qualityProfileId'");
            }
            resourceInputs["metadataProfileId"] = args ? args.metadataProfileId : undefined;
            resourceInputs["monitorOption"] = args ? args.monitorOption : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["newItemMonitorOption"] = args ? args.newItemMonitorOption : undefined;
            resourceInputs["path"] = args ? args.path : undefined;
            resourceInputs["qualityProfileId"] = args ? args.qualityProfileId : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["accessible"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RootFolder.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RootFolder resources.
 */
export interface RootFolderState {
    /**
     * Access flag.
     */
    accessible?: pulumi.Input<boolean>;
    /**
     * Metadata profile ID.
     */
    metadataProfileId?: pulumi.Input<number>;
    /**
     * Monitor option.
     */
    monitorOption?: pulumi.Input<string>;
    /**
     * Root Folder friendly name.
     */
    name?: pulumi.Input<string>;
    /**
     * New item monitor option.
     */
    newItemMonitorOption?: pulumi.Input<string>;
    /**
     * Root Folder absolute path.
     */
    path?: pulumi.Input<string>;
    /**
     * Quality profile ID.
     */
    qualityProfileId?: pulumi.Input<number>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
}

/**
 * The set of arguments for constructing a RootFolder resource.
 */
export interface RootFolderArgs {
    /**
     * Metadata profile ID.
     */
    metadataProfileId: pulumi.Input<number>;
    /**
     * Monitor option.
     */
    monitorOption: pulumi.Input<string>;
    /**
     * Root Folder friendly name.
     */
    name: pulumi.Input<string>;
    /**
     * New item monitor option.
     */
    newItemMonitorOption: pulumi.Input<string>;
    /**
     * Root Folder absolute path.
     */
    path: pulumi.Input<string>;
    /**
     * Quality profile ID.
     */
    qualityProfileId: pulumi.Input<number>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
}
