// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Import Lists -->Import List Exclusion resource.
 * For more information refer to [ImportListExclusions](https://wiki.servarr.com/lidarr/settings#list-exclusions) documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as lidarr from "@maienm/pulumi-lidarr";
 *
 * const example = new lidarr.importlists.ImportListExclusion("example", {
 *     artistName: "Queen",
 *     foreignId: "0383dadf-2a4e-4d10-a46a-e9e041da8eb3",
 * });
 * ```
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import lidarr:ImportLists/importListExclusion:ImportListExclusion example 10
 * ```
 */
export class ImportListExclusion extends pulumi.CustomResource {
    /**
     * Get an existing ImportListExclusion resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ImportListExclusionState, opts?: pulumi.CustomResourceOptions): ImportListExclusion {
        return new ImportListExclusion(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lidarr:ImportLists/importListExclusion:ImportListExclusion';

    /**
     * Returns true if the given object is an instance of ImportListExclusion.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ImportListExclusion {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ImportListExclusion.__pulumiType;
    }

    /**
     * Artist to be excluded.
     */
    public readonly artistName!: pulumi.Output<string>;
    /**
     * Musicbrainz ID.
     */
    public readonly foreignId!: pulumi.Output<string>;

    /**
     * Create a ImportListExclusion resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ImportListExclusionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ImportListExclusionArgs | ImportListExclusionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ImportListExclusionState | undefined;
            resourceInputs["artistName"] = state ? state.artistName : undefined;
            resourceInputs["foreignId"] = state ? state.foreignId : undefined;
        } else {
            const args = argsOrState as ImportListExclusionArgs | undefined;
            if ((!args || args.artistName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'artistName'");
            }
            if ((!args || args.foreignId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'foreignId'");
            }
            resourceInputs["artistName"] = args ? args.artistName : undefined;
            resourceInputs["foreignId"] = args ? args.foreignId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ImportListExclusion.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ImportListExclusion resources.
 */
export interface ImportListExclusionState {
    /**
     * Artist to be excluded.
     */
    artistName?: pulumi.Input<string>;
    /**
     * Musicbrainz ID.
     */
    foreignId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ImportListExclusion resource.
 */
export interface ImportListExclusionArgs {
    /**
     * Artist to be excluded.
     */
    artistName: pulumi.Input<string>;
    /**
     * Musicbrainz ID.
     */
    foreignId: pulumi.Input<string>;
}
