// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace Artists {
    export interface GetArtistsArtist {
        /**
         * Artist name.
         */
        artistName: string;
        /**
         * Foreign artist ID.
         */
        foreignArtistId: string;
        /**
         * List genres.
         */
        genres: string[];
        /**
         * Artist ID.
         */
        id: number;
        /**
         * Metadata profile ID.
         */
        metadataProfileId: number;
        /**
         * Monitored flag.
         */
        monitored: boolean;
        /**
         * Overview.
         */
        overview: string;
        /**
         * Full artist path.
         */
        path: string;
        /**
         * Quality profile ID.
         */
        qualityProfileId: number;
        /**
         * Artist status.
         */
        status: string;
        /**
         * List of associated tags.
         */
        tags: number[];
    }

}

export namespace DownloadClients {
    export interface GetDownloadClientsDownloadClient {
        /**
         * Add paused flag.
         */
        addPaused: boolean;
        /**
         * Add stopped flag.
         */
        addStopped: boolean;
        /**
         * Additional tags, `0` TitleSlug, `1` Quality, `2` Language, `3` ReleaseGroup, `4` Year, `5` Indexer, `6` Network.
         */
        additionalTags: number[];
        /**
         * API key.
         */
        apiKey: string;
        /**
         * Category.
         */
        category: string;
        /**
         * DownloadClient configuration template.
         */
        configContract: string;
        /**
         * Destination.
         */
        destination: string;
        /**
         * Enable flag.
         */
        enable: boolean;
        /**
         * Field tags.
         */
        fieldTags: string[];
        /**
         * First and last flag.
         */
        firstAndLast: boolean;
        /**
         * host.
         */
        host: string;
        /**
         * Download Client ID.
         */
        id: number;
        /**
         * DownloadClient implementation name.
         */
        implementation: string;
        /**
         * Initial state. `0` Start, `1` ForceStart, `2` Pause.
         */
        initialState: number;
        /**
         * Initial state, with Stop support. `0` Start, `1` ForceStart, `2` Pause, `3` Stop.
         */
        intialState: number;
        /**
         * Magnet file extension.
         */
        magnetFileExtension: string;
        /**
         * Music category.
         */
        musicCategory: string;
        /**
         * Music directory.
         */
        musicDirectory: string;
        /**
         * Music imported category.
         */
        musicImportedCategory: string;
        /**
         * Download Client name.
         */
        name: string;
        /**
         * NZB folder.
         */
        nzbFolder: string;
        /**
         * Older Music priority. `0` Last, `1` First.
         */
        olderMusicPriority: number;
        /**
         * Password.
         */
        password: string;
        /**
         * Port.
         */
        port: number;
        /**
         * Post import tags.
         */
        postImportTags: string[];
        /**
         * Priority.
         */
        priority: number;
        /**
         * Protocol. Valid values are 'usenet' and 'torrent'.
         */
        protocol: string;
        /**
         * Read only flag.
         */
        readOnly: boolean;
        /**
         * Recent Music priority. `0` Last, `1` First.
         */
        recentMusicPriority: number;
        /**
         * Remove completed downloads flag.
         */
        removeCompletedDownloads: boolean;
        /**
         * Remove failed downloads flag.
         */
        removeFailedDownloads: boolean;
        /**
         * RPC path.
         */
        rpcPath: string;
        /**
         * Save magnet files flag.
         */
        saveMagnetFiles: boolean;
        /**
         * Secret token.
         */
        secretToken: string;
        /**
         * Sequential order flag.
         */
        sequentialOrder: boolean;
        /**
         * Start on add flag.
         */
        startOnAdd: boolean;
        /**
         * STRM folder.
         */
        strmFolder: string;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Torrent folder.
         */
        torrentFolder: string;
        /**
         * Base URL.
         */
        urlBase: string;
        /**
         * Use SSL flag.
         */
        useSsl: boolean;
        /**
         * Username.
         */
        username: string;
        /**
         * Watch folder flag.
         */
        watchFolder: string;
    }

    export interface GetRemotePathMappingsRemotePathMapping {
        /**
         * Download Client host.
         */
        host: string;
        /**
         * RemotePathMapping ID.
         */
        id: number;
        /**
         * Local path.
         */
        localPath: string;
        /**
         * Download Client remote path.
         */
        remotePath: string;
    }

}

export namespace ImportLists {
    export interface GetImportListExclusionsImportListExclusion {
        /**
         * Artist to be excluded.
         */
        artistName: string;
        /**
         * Musicbrainz ID.
         */
        foreignId: string;
        /**
         * ImportListExclusion ID.
         */
        id: number;
    }

    export interface GetImportListsImportList {
        /**
         * Access token.
         */
        accessToken: string;
        /**
         * API key.
         */
        apiKey: string;
        /**
         * Base URL.
         */
        baseUrl: string;
        /**
         * ImportList configuration template.
         */
        configContract: string;
        /**
         * Elements to pull from list.
         */
        countList: number;
        /**
         * Enable automatic add flag.
         */
        enableAutomaticAdd: boolean;
        /**
         * Expires.
         */
        expires: string;
        /**
         * Import List ID.
         */
        id: number;
        /**
         * ImportList implementation name.
         */
        implementation: string;
        /**
         * List ID.
         */
        listId: string;
        /**
         * List order.
         */
        listOrder: number;
        /**
         * List type.
         */
        listType: string;
        /**
         * Metadata profile ID.
         */
        metadataProfileId: number;
        /**
         * Monitor new items.
         */
        monitorNewItems: string;
        /**
         * Import List name.
         */
        name: string;
        /**
         * Playlist IDs.
         */
        playlistIds: string[];
        /**
         * Profile IDs.
         */
        profileIds: number[];
        /**
         * Quality profile ID.
         */
        qualityProfileId: number;
        /**
         * Refresh token.
         */
        refreshToken: string;
        /**
         * Root folder path.
         */
        rootFolderPath: string;
        /**
         * Series ID.
         */
        seriesId: string;
        /**
         * Should monitor.
         */
        shouldMonitor: string;
        /**
         * Should monitor existing flag.
         */
        shouldMonitorExisting: boolean;
        /**
         * Should search flag.
         */
        shouldSearch: boolean;
        /**
         * Tag ID.
         */
        tagId: string;
        /**
         * Tag IDs.
         */
        tagIds: number[];
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * User ID.
         */
        userId: string;
    }

}

export namespace Indexers {
    export interface GetIndexersIndexer {
        /**
         * Additional parameters.
         */
        additionalParameters: string;
        /**
         * Allow zero size files.
         */
        allowZeroSize: boolean;
        /**
         * API key.
         */
        apiKey: string;
        /**
         * API path.
         */
        apiPath: string;
        /**
         * API User.
         */
        apiUser: string;
        /**
         * Base URL.
         */
        baseUrl: string;
        /**
         * Captcha token.
         */
        captchaToken: string;
        /**
         * Series list.
         */
        categories: number[];
        /**
         * Indexer configuration template.
         */
        configContract: string;
        /**
         * Cookie.
         */
        cookie: string;
        /**
         * Delay before grabbing.
         */
        delay: number;
        /**
         * Discography seed time.
         */
        discographySeedTime: number;
        /**
         * Early release limit.
         */
        earlyReleaseLimit: number;
        /**
         * Enable automatic search flag.
         */
        enableAutomaticSearch: boolean;
        /**
         * Enable interactive search flag.
         */
        enableInteractiveSearch: boolean;
        /**
         * Enable RSS flag.
         */
        enableRss: boolean;
        /**
         * Indexer ID.
         */
        id: number;
        /**
         * Indexer implementation name.
         */
        implementation: string;
        /**
         * Minimum seeders.
         */
        minimumSeeders: number;
        /**
         * Indexer name.
         */
        name: string;
        /**
         * Passkey.
         */
        passkey: string;
        /**
         * Password.
         */
        password: string;
        /**
         * Priority.
         */
        priority: number;
        /**
         * Protocol. Valid values are 'usenet' and 'torrent'.
         */
        protocol: string;
        /**
         * Allow ranked only.
         */
        rankedOnly: boolean;
        /**
         * RSS passkey.
         */
        rssPasskey: string;
        /**
         * Seed ratio.
         */
        seedRatio: number;
        /**
         * Seed time.
         */
        seedTime: number;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Use freeleech token flag.
         */
        useFreeleechToken: boolean;
        /**
         * User ID.
         */
        userId: string;
        /**
         * Username.
         */
        username: string;
    }

}

export namespace MediaManagement {
    export interface GetRootFoldersRootFolder {
        /**
         * Access flag.
         */
        accessible: boolean;
        /**
         * Root Folder ID.
         */
        id: number;
        /**
         * Metadata profile ID.
         */
        metadataProfileId: number;
        /**
         * Monitor option.
         */
        monitorOption: string;
        /**
         * Root Folder friendly name.
         */
        name: string;
        /**
         * New item monitor option.
         */
        newItemMonitorOption: string;
        /**
         * Root Folder absolute path.
         */
        path: string;
        /**
         * Quality profile ID.
         */
        qualityProfileId: number;
        /**
         * List of associated tags.
         */
        tags: number[];
    }

}

export namespace Metadata {
    export interface GetMetadataConsumersMetadataConsumer {
        /**
         * Album images flag.
         */
        albumImages: boolean;
        /**
         * Album metadata flag.
         */
        albumMetadata: boolean;
        /**
         * Artist images flag.
         */
        artistImages: boolean;
        /**
         * Artist metadata flag.
         */
        artistMetadata: boolean;
        /**
         * Metadata configuration template.
         */
        configContract: string;
        /**
         * Enable flag.
         */
        enable: boolean;
        /**
         * Metadata ID.
         */
        id: number;
        /**
         * Metadata implementation name.
         */
        implementation: string;
        /**
         * Metadata name.
         */
        name: string;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Track metadata flag.
         */
        trackMetadata: boolean;
    }

}

export namespace Notifications {
    export interface GetNotificationsNotification {
        /**
         * Access token.
         */
        accessToken: string;
        /**
         * Access token secret.
         */
        accessTokenSecret: string;
        /**
         * Always update flag.
         */
        alwaysUpdate: boolean;
        /**
         * API key.
         */
        apiKey: string;
        /**
         * App token.
         */
        appToken: string;
        /**
         * Arguments.
         */
        arguments: string;
        /**
         * Password.
         */
        authPassword: string;
        /**
         * Auth token.
         */
        authToken: string;
        /**
         * Auth user.
         */
        authUser: string;
        /**
         * Username.
         */
        authUsername: string;
        /**
         * Author.
         */
        author: string;
        /**
         * Avatar.
         */
        avatar: string;
        /**
         * Bcc.
         */
        bccs: string[];
        /**
         * Bot token.
         */
        botToken: string;
        /**
         * Cc.
         */
        ccs: string[];
        /**
         * Channel.
         */
        channel: string;
        /**
         * Channel tags.
         */
        channelTags: string[];
        /**
         * Chat ID.
         */
        chatId: string;
        /**
         * Clean library flag.
         */
        cleanLibrary: boolean;
        /**
         * Click URL.
         */
        clickUrl: string;
        /**
         * Notification configuration template.
         */
        configContract: string;
        /**
         * Configuration key.
         */
        configurationKey: string;
        /**
         * Consumer key.
         */
        consumerKey: string;
        /**
         * Consumer secret.
         */
        consumerSecret: string;
        /**
         * Device IDs.
         */
        deviceIds: string[];
        /**
         * Device names.
         */
        deviceNames: string;
        /**
         * Devices.
         */
        devices: string[];
        /**
         * Direct message flag.
         */
        directMessage: boolean;
        /**
         * Display time.
         */
        displayTime: number;
        /**
         * Event.
         */
        event: string;
        /**
         * Expire.
         */
        expire: number;
        /**
         * Expires.
         */
        expires: string;
        /**
         * Tags and emojis.
         */
        fieldTags: string[];
        /**
         * From.
         */
        from: string;
        /**
         * Grab fields. `0` Overview, `1` Rating, `2` Genres, `3` Quality, `4` Group, `5` Size, `6` Links, `7` Release, `8` Poster, `9` Fanart.
         */
        grabFields: number[];
        /**
         * Host.
         */
        host: string;
        /**
         * Icon.
         */
        icon: string;
        /**
         * Notification ID.
         */
        id: number;
        /**
         * Notification implementation name.
         */
        implementation: string;
        /**
         * Import fields. `0` Overview, `1` Rating, `2` Genres, `3` Quality, `4` Codecs, `5` Group, `6` Size, `7` Languages, `8` Subtitles, `9` Links, `10` Release, `11` Poster, `12` Fanart.
         */
        importFields: number[];
        /**
         * Include health warnings.
         */
        includeHealthWarnings: boolean;
        /**
         * Key.
         */
        key: string;
        /**
         * Mention.
         */
        mention: string;
        /**
         * Method. `1` POST, `2` PUT.
         */
        method: number;
        /**
         * Notification name.
         */
        name: string;
        /**
         * Notification type. `0` Info, `1` Success, `2` Warning, `3` Failure.
         */
        notificationType: number;
        /**
         * Notify flag.
         */
        notify: boolean;
        /**
         * On album delete flag.
         */
        onAlbumDelete: boolean;
        /**
         * On application update flag.
         */
        onApplicationUpdate: boolean;
        /**
         * On artist delete flag.
         */
        onArtistDelete: boolean;
        /**
         * On download failure flag.
         */
        onDownloadFailure: boolean;
        /**
         * On grab flag.
         */
        onGrab: boolean;
        /**
         * On health issue flag.
         */
        onHealthIssue: boolean;
        /**
         * On health restored flag.
         */
        onHealthRestored: boolean;
        /**
         * On import failure flag.
         */
        onImportFailure: boolean;
        /**
         * On release import flag.
         */
        onReleaseImport: boolean;
        /**
         * On rename flag.
         */
        onRename: boolean;
        /**
         * On track retag.
         */
        onTrackRetag: boolean;
        /**
         * On upgrade flag.
         */
        onUpgrade: boolean;
        /**
         * password.
         */
        password: string;
        /**
         * Path.
         */
        path: string;
        /**
         * Port.
         */
        port: number;
        /**
         * Priority.
         */
        priority: number;
        /**
         * Receiver ID.
         */
        receiverId: string;
        /**
         * Recipients.
         */
        recipients: string[];
        /**
         * Refresh token.
         */
        refreshToken: string;
        /**
         * Require encryption flag.
         */
        requireEncryption: boolean;
        /**
         * Retry.
         */
        retry: number;
        /**
         * Add silently flag.
         */
        sendSilently: boolean;
        /**
         * Sender domain.
         */
        senderDomain: string;
        /**
         * Sender ID.
         */
        senderId: string;
        /**
         * Sender Number.
         */
        senderNumber: string;
        /**
         * server.
         */
        server: string;
        /**
         * Server URL.
         */
        serverUrl: string;
        /**
         * Sign in.
         */
        signIn: string;
        /**
         * Sound.
         */
        sound: string;
        /**
         * Stateless URLs.
         */
        statelessUrls: string;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Token.
         */
        token: string;
        /**
         * Topics.
         */
        topics: string[];
        /**
         * To.
         */
        tos: string[];
        /**
         * Update library flag.
         */
        updateLibrary: boolean;
        /**
         * URL.
         */
        url: string;
        /**
         * URL base.
         */
        urlBase: string;
        /**
         * Use EU endpoint flag.
         */
        useEuEndpoint: boolean;
        /**
         * Use SSL flag.
         */
        useSsl: boolean;
        /**
         * User key.
         */
        userKey: string;
        /**
         * Username.
         */
        username: string;
        /**
         * Web hook url.
         */
        webHookUrl: string;
    }

}

export namespace Profiles {
    export interface CustomFormatSpecification {
        /**
         * Implementation.
         */
        implementation: string;
        /**
         * Max.
         */
        max: number;
        /**
         * Min.
         */
        min: number;
        /**
         * Specification name.
         */
        name: string;
        /**
         * Negate flag.
         */
        negate: boolean;
        /**
         * Required flag.
         */
        required: boolean;
        /**
         * Value.
         */
        value: string;
    }

    export interface GetCustomFormatSpecification {
        /**
         * Implementation.
         */
        implementation: string;
        /**
         * Max.
         */
        max: number;
        /**
         * Min.
         */
        min: number;
        /**
         * Specification name.
         */
        name: string;
        /**
         * Negate flag.
         */
        negate: boolean;
        /**
         * Computed flag.
         */
        required: boolean;
        /**
         * Value.
         */
        value: string;
    }

    export interface GetCustomFormatsCustomFormat {
        /**
         * Custom Format ID.
         */
        id: number;
        /**
         * Include custom format when renaming flag.
         */
        includeCustomFormatWhenRenaming: boolean;
        /**
         * Custom Format name.
         */
        name: string;
        /**
         * Specifications.
         */
        specifications: outputs.Profiles.GetCustomFormatsCustomFormatSpecification[];
    }

    export interface GetCustomFormatsCustomFormatSpecification {
        implementation: string;
        max: number;
        min: number;
        name: string;
        negate: boolean;
        required: boolean;
        value: string;
    }

    export interface GetDelayProfilesDelayProfile {
        /**
         * Torrent allowed Flag.
         */
        enableTorrent: boolean;
        /**
         * Usenet allowed Flag.
         */
        enableUsenet: boolean;
        /**
         * Delay Profile ID.
         */
        id: number;
        /**
         * Order.
         */
        order: number;
        /**
         * Preferred protocol.
         */
        preferredProtocol: string;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Torrent Delay.
         */
        torrentDelay: number;
        /**
         * Usenet delay.
         */
        usenetDelay: number;
    }

    export interface GetMetadataProfilesMetadataProfile {
        /**
         * Metadata Profile ID.
         */
        id: number;
        /**
         * Metadata Profile name.
         */
        name: string;
        /**
         * Primary album types.
         */
        primaryAlbumTypes: number[];
        /**
         * Release statuses.
         */
        releaseStatuses: number[];
        /**
         * Secondary album types.
         */
        secondaryAlbumTypes: number[];
    }

    export interface GetPrimaryAlbumTypesElement {
        /**
         * Album type ID.
         */
        id: number;
        /**
         * Album type name.
         */
        name: string;
    }

    export interface GetQualityDefinitionsQualityDefinition {
        /**
         * Quality Definition ID.
         */
        id: number;
        /**
         * Maximum size MB/min.
         */
        maxSize: number;
        /**
         * Minimum size MB/min.
         */
        minSize: number;
        /**
         * Quality ID.
         */
        qualityId: number;
        /**
         * Quality Name.
         */
        qualityName: string;
        /**
         * Quality Definition Title.
         */
        title: string;
    }

    export interface GetQualityProfileFormatItem {
        /**
         * Format.
         */
        format: number;
        /**
         * Name.
         */
        name: string;
        /**
         * Score.
         */
        score: number;
    }

    export interface GetQualityProfileQualityGroup {
        /**
         * Quality group ID.
         */
        id: number;
        /**
         * Quality group name.
         */
        name: string;
        /**
         * Qualities in group.
         */
        qualities: outputs.Profiles.GetQualityProfileQualityGroupQuality[];
    }

    export interface GetQualityProfileQualityGroupQuality {
        /**
         * Quality Profile ID.
         */
        id: number;
        /**
         * Quality Profile Name.
         */
        name: string;
    }

    export interface GetQualityProfilesQualityProfile {
        /**
         * Quality ID to which cutoff.
         */
        cutoff: number;
        /**
         * Cutoff format score.
         */
        cutoffFormatScore: number;
        /**
         * Format items.
         */
        formatItems: outputs.Profiles.GetQualityProfilesQualityProfileFormatItem[];
        /**
         * Quality Profile ID.
         */
        id: number;
        /**
         * Min format score.
         */
        minFormatScore: number;
        /**
         * Quality Profile Name.
         */
        name: string;
        /**
         * Quality groups.
         */
        qualityGroups: outputs.Profiles.GetQualityProfilesQualityProfileQualityGroup[];
        /**
         * Upgrade allowed flag.
         */
        upgradeAllowed: boolean;
    }

    export interface GetQualityProfilesQualityProfileFormatItem {
        format: number;
        name: string;
        score: number;
    }

    export interface GetQualityProfilesQualityProfileQualityGroup {
        /**
         * The ID of this resource.
         */
        id: number;
        name: string;
        qualities: outputs.Profiles.GetQualityProfilesQualityProfileQualityGroupQuality[];
    }

    export interface GetQualityProfilesQualityProfileQualityGroupQuality {
        /**
         * The ID of this resource.
         */
        id: number;
        name: string;
    }

    export interface GetReleaseProfilesReleaseProfile {
        /**
         * Enabled.
         */
        enabled: boolean;
        /**
         * Release Profile ID.
         */
        id: number;
        /**
         * Ignored terms. At least one of `required` and `ignored` must be set.
         */
        ignoreds: string[];
        /**
         * Indexer ID.
         */
        indexerId: number;
        /**
         * Required terms. At least one of `required` and `ignored` must be set.
         */
        requireds: string[];
        /**
         * List of associated tags.
         */
        tags: number[];
    }

    export interface GetReleaseStatusesElement {
        /**
         * Release status ID.
         */
        id: number;
        /**
         * Release status name.
         */
        name: string;
    }

    export interface GetSecondaryAlbumTypesElement {
        /**
         * Album type ID.
         */
        id: number;
        /**
         * Album type name.
         */
        name: string;
    }

    export interface QualityProfileFormatItem {
        /**
         * Format.
         */
        format: number;
        /**
         * Name.
         */
        name: string;
        /**
         * Score.
         */
        score: number;
    }

    export interface QualityProfileQualityGroup {
        /**
         * Quality group ID.
         */
        id: number;
        /**
         * Quality group name.
         */
        name: string;
        /**
         * Qualities in group.
         */
        qualities: outputs.Profiles.QualityProfileQualityGroupQuality[];
    }

    export interface QualityProfileQualityGroupQuality {
        /**
         * Quality Profile ID.
         */
        id: number;
        /**
         * Quality Profile Name.
         */
        name: string;
    }

}

export namespace Tags {
    export interface GetTagsTag {
        /**
         * Tag ID.
         */
        id: number;
        /**
         * Tag label.
         */
        label: string;
    }

}
